# 開發環境專用的 Docker Compose 覆蓋配置
version: '3.8'

services:
  backend:
    environment:
      - ENVIRONMENT=development
    volumes:
      - ./backend:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["pnpm", "run", "dev"]

  agent-hub:
    environment:
      - ENVIRONMENT=development
    volumes:
      - ./agent-hub:/app
    command: ["python", "-m", "src.main"]

