services:
  - type: web
    name: morningai-api
    env: python
    plan: starter
    region: singapore
    rootDir: backend
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ALLOW_ORIGINS
        value: https://morningai-project.vercel.app,https://*.vercel.app
    healthCheckPath: /health
    autoDeploy: true

